### ISSUE TITLE
SimpleHTTPServer

### ISSUE THREAD

**Issue by dfinke** [TLaborde/NodePS#3]
This looks great. I've used the SimpleHTTPServer in python.

It'd be great if the parameters could be shuffled for this to be to work (with the Port Position=0)
`Start-NodePSServer  8000`

Also, maybe by default the `-HomeDirectory` could be `$pwd`?

Only because I work with a python folks and to be able to point them at this and it just works. I can walk them through creating an alias for SimpleHTTPServer  to the function name.

https://docs.python.org/2/library/simplehttpserver.html

`-HomeDirectory .`   didn't seem to work.

Thanks
Doug

**Comment by TLaborde** [comment]
ah, I understood your second point. I think you need to do "-homeDirectory ./" Maybe i need to add more resolve-path...

and for shuffling the order or parameters, you could do a proxy function for that?
